### ISSUE TITLE
email-sendgrid not visible

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-email-sendgrid#1]
I'm running Grav v1.7.41.1
I've installed the latest email plugin.
I've installed the email-sendgrid plugin

I cannot select Mail Engine **Sendgrid** in the email plugin

![image](https://github.com/getgrav/grav-plugin-email-sendgrid/assets/12153667/14630172-0c29-4a82-9449-325e8f16cee5)

and I cannot find the email-sendgrid plugin in the list of installed plugins.

What could be the cause of this?

**Comment by danjames68** [comment]
It looks like the installer names the plugin folder incorrectly, as "email-sengrid" instead of "email-sendgrid". Renaming the folder makes it appear in the options - and in the list of plugins. But the installer will need correcting, something I can't do.

**Comment by awrog** [comment]
🤔 In my installation the plugin folder is named correctly (based on the plugin `getgrav-grav-plugin-email-sendgrid-1.0.0-0-g5f555fc.zip`).
It also shows up in the list of Mail engines in the Email plugin.
Looks like it is working now...

**Comment by petrus9** [comment]
This is still happening for me:  Grav v1.7.45, also another bug, is if you install the sendgrid plugin and it shows up after renaming the folder as @danjames68 mentioned.   Then adding sendgrid as sender in the Email plugin, the website errors out.  Have to then manually add the API key to the yaml file in the sendgrid plugin folder to get the site working again.

**Comment by rhukster** [comment]
Found the issue!  it was not in the plugin, but actually in the GPM repository entry itself!  i've fixed this now and after GPM runs (in about 10 mins) it should install and work just fine going forward.  Sorry for the delay but i had previous checked everything in the plugin and it all looked good.
